import type { Metadata } from "next";
import { Inter } from "next/font/google"
import "./globals.css";
import Header from "./header";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.className} antialiased justify-center items-center`}
            >
                <div className="flex items-center justify-center min-h-screen bg-gray-100">
                    <div className="bg-white p-8 rounded-lg shadow-md w-full max-w-sm flex flex-col items-center justify-center">
                        <Header></Header>
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}